version: '3.8'

services:
  db:
    image: postgres:15
    container_name: sql-injection-lab-db
    environment:
      POSTGRES_DB: sqli_lab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sqli-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sql-injection-lab-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/sqli_lab
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    depends_on:
      db:
        condition: service_started
    networks:
      - sqli-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sql-injection-lab-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sqlilab.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
    ports:
      - "8888:80"
    depends_on:
      - db
    networks:
      - sqli-network
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpassfile:/tmp/pgpassfile

volumes:
  postgres_data:
  pgadmin_data:

networks:
  sqli-network:
    driver: bridge
