version: '3.8'

services:
  db:
    image: postgres:15
    container_name: sqli-lab-db-dev
    environment:
      POSTGRES_DB: sqli_lab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sqli-network-dev

  app:
    image: node:18-alpine
    container_name: sqli-lab-app-dev
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/sqli_lab
      JWT_SECRET: dev-secret-key
      NODE_ENV: development
    depends_on:
      - db
    networks:
      - sqli-network-dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data_dev:

networks:
  sqli-network-dev:
    driver: bridge
